import Head from "next/head";
import Link from "next/link";

import type { NextPage } from "next";

import { Layout } from "@/components/layouts";
import { getSortedPostsData, PostData } from "@/lib/posts";

type Props = {
  allPostsData: PostData[];
};

const Home: NextPage<Props> = ({ allPostsData }: Props) => {
  return (
    <Layout>
      <Head>
        <title>to10</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>
          Learn <Link href="https://nextjs.org">Next.js!</Link>
          <br />
          And READ <Link href="/posts/first-posts">First Posts!</Link>
        </h1>
        <div>
          {allPostsData.map(({ id, date, title }) => {
            return (
              <div key={id}>
                <ul>
                  <li>{id}</li>
                  <li>{title}</li>
                  <li>{date}</li>
                </ul>
              </div>
            );
          })}
        </div>
      </main>
    </Layout>
  );
};

export default Home;

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}
